### ISSUE TITLE
Post Comments

### ISSUE THREAD

**Issue by MalikWhitten67** [Postr-Inc/pwa#6]
Upon clicking the comment button users shall be able to read comments - but also like and reply to them

**Comment by arabianpulse** [comment]
Working on it.

**Comment by im-haz** [comment]
Don't know whether I've done this right, please review before push

https://cdn.discordapp.com/attachments/1139692636807110717/1145491242533269524/post.js

**Comment by haz7a-sudo** [comment]
Don't know whether I've done this right, please review before push

https://cdn.discordapp.com/attachments/1139692636807110717/1145491242533269524/post.js
